name: Redeploy Next.js Site to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Redeploy to Vercel via Webhook
        run: curl -s -X POST "${{ secrets.VERCEL_REDEPLOY_WEBHOOK_URL }}"
